version: '3'
services:
  app:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    depends_on:
      - db
    # vm_app:
        #  build: ~/liga/HomeWork_HTTP/
        #  ports:
        #   - "8080:5678"
    #        depends_on:
    #         - redis
    #      redis:
    #        image: redis
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:


