version: '3'
services:
  app:
    build:
      context: ./
      target: development
    command: rails s -b 0.0.0.0
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"

    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    
    # vm_app:
        #  build: ~/liga/HomeWork_HTTP/
        #  ports:
        #   - "8080:5678"
    #        depends_on:
    #         - redis
    #      redis:
    #        image: redis
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  sidekiq:
    build: .
    command: sidekiq
    volumes:
      - .:/usr/src
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    tmpfs:
      - /usr/src/tmp/pids

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - rabbit:/var/lib/rabbitmq
    
  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data
    

volumes:
  postgres:
  redis:
  rabbit:

